my_site/my_site/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from p_library import views
from django.conf.urls.static import static
from allauth.account.views import login, logout, signup
from p_library.views import profile, CreateUserProfile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', views.index, name='my-library'),
    path('index/book_increment/', views.book_increment),
    path('index/book_decrement/', views.book_decrement),
    path('publishes/', views.redactions, name='publishes'),
    path('authors/', include('p_library.urls')),
    path('accounts/', include('allauth.urls')),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('register/', signup, name='register'),
    path('profile/', profile, name='profile-page'),
    path('profile-create/', CreateUserProfile.as_view(), name='profile-create'),
    path('', views.index_redirect),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_site/p_library/urls.py
from django.urls import path
from .views import AuthorEdit, AuthorList, author_create_many, books_authors_create_many

app_name = 'p_library'
urlpatterns = [
    path('', AuthorList.as_view(), name='author_list'),
    path('create/', AuthorEdit.as_view(), name='author_create'),
    path('create_many/', author_create_many, name='author_create_many'),
    path('create_book_many/', books_authors_create_many, name='author_book_create_many'),
]

my_site/p_library/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    age = models.IntegerField(default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user} - {self.age} years old'


class Authors(models.Model):
    """ Author model """
    full_name = models.TextField(max_length=50)
    birth_year = models.SmallIntegerField()
    country = models.CharField(max_length=2)

    def __str__(self):
        return self.full_name


class Book(models.Model):
    """ Book model """
    ISBN = models.CharField(max_length=13)
    title = models.CharField(max_length=128)
    description = models.TextField()
    year_release = models.SmallIntegerField()
    author = models.ForeignKey(Authors, on_delete=models.CASCADE, default='')
    copy_count = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    redaction = models.ForeignKey('Redaction', on_delete=models.CASCADE, null=True, blank=True, related_name='books')
    reader = models.ForeignKey('Reader', on_delete=models.CASCADE, null=True, blank=True, related_name='books')
    image = models.ImageField(upload_to='media', default='default.png')

    def __str__(self):
        return self.title


class Inspiration(models.Model):
    """ Inspiration model """
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Authors, on_delete=models.CASCADE)
    inspirer = models.ForeignKey(
        Authors,
        on_delete=models.CASCADE,
        related_name='inspired_works',
    )

    def __str__(self):
        return f'{self.book} - {self.author} - {self.inspirer}'


class Redaction(models.Model):
    """ Redaction model """
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class Reader(models.Model):
    """ Reader model """
    full_name = models.TextField()
    birth_year = models.SmallIntegerField()

    def __str__(self):
        return self.full_name

my_site/p_library/forms.py
from django import forms
from .models import Authors, Book, UserProfile


class AuthorForm(forms.ModelForm):
    full_name = forms.CharField(widget=forms.TextInput)

    class Meta:
        model = Authors
        fields = '__all__'


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'


class ProfileCreationForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['age']

my_site/p_library/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from .models import Book, Redaction, Authors, UserProfile
from .forms import AuthorForm, BookForm, ProfileCreationForm
from django.views.generic import CreateView, ListView, FormView
from django.urls import reverse_lazy
from django.forms import formset_factory
from django.http.response import HttpResponseRedirect
from allauth.socialaccount.models import SocialAccount


def index_redirect(request):
    return redirect('library/', request)


def profile(request):
    context = {}
    if request.user.is_authenticated:
        context['username'] = request.user.username
        if SocialAccount.objects.get(provider='github', user=request.user):
            git_account = SocialAccount.objects.get(
                provider='github',
                user=request.user
            )
            context['github_url'] = git_account.extra_data['html_url']
            # context['age'] = git_account.extra_data['age']
        else:
            sys_user = UserProfile.objects.get(user=request.user)
            context['age'] = sys_user.age
            context['github_url'] = ''
    return render(request, 'profile.html', context)


class CreateUserProfile(FormView):
    form_class = ProfileCreationForm
    template_name = 'profile-create.html'
    success_url = reverse_lazy('profile-page')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('login'))
        return super(CreateUserProfile, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        try:
            if SocialAccount.objects.get(provider='github', user_id=self.request.user.id):
                git_age = SocialAccount.objects.get(
                    provider='github',
                    user=self.request.user
                )
                git_age.extra_data['age'] = str(form['age'].value())
                git_age.save()
        except:
            user_age = UserProfile.objects.get(
                user=self.request.user
            )
            print(user_age.age)
            user_age.age = str(form['age'].value())
            user_age.save()

        return super(CreateUserProfile, self).form_valid(form)


def index(request):
    template = loader.get_template('library.html')
    books = Book.objects.all()
    biblio_data = {
        "title": "my library",
        "books": books,
    }
    return HttpResponse(template.render(biblio_data, request))


@csrf_exempt
def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            book.copy_count += 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')


@csrf_exempt
def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')


def redactions(request):
    template = loader.get_template('publishes.html')
    redactions = Redaction.objects.all()
    data = {
        "redactions": redactions,
    }
    return HttpResponse(template.render(data, request))


class AuthorEdit(CreateView):
    model = Authors
    form_class = AuthorForm
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_edit.html'


class AuthorList(ListView):
    model = Authors
    template_name = 'author_list.html'


def author_create_many(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    if request.method == 'POST':
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')
        if author_formset.is_valid():
            for author_form in author_formset:
                author_form.save()
            return HttpResponseRedirect(
                reverse_lazy('p_library:author_list'))
    else:
        author_formset = AuthorFormSet(prefix='authors')
    return render(request, 'manage_authors.html', {'author_formset': author_formset})


def books_authors_create_many(request):
    AuthorFormSet = formset_factory(AuthorForm, extra=2)
    BookFormSet = formset_factory(BookForm, extra=2)
    if request.method == 'POST':
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')
        if author_formset.is_valid() and book_formset.is_valid():
            for author_form in author_formset:
                author_form.save()
            for book_form in book_formset:
                book_form.save()
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))
    else:
        author_formset = AuthorFormSet(prefix='authors')
        book_formset = BookFormSet(prefix='books')
    return render(
        request,
        'manage_books_authors.html',
        {
            'author_formset': author_formset,
            'book_formset': book_formset,
        }
    )

my_site/p_library/templates/author-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {#  bootstrap  #}
    {#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"#}
    {#          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">#}
    {#  materializecss  #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/media' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>My Home Virtual Library</title>
</head>
<body>
<nav>
    <div class="nav-wrapper purple darken-2">
        <a href="{% url 'my-library' %}" class="brand-logo">My Home Virtual Library</a>
        <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'p_library:author_list' %}">Authors</a></li>
            <li><a href="{% url 'p_library:author_create' %}">Add Author</a></li>
            <li><a href="{% url 'p_library:author_book_create_many' %}">Add Book</a></li>
            <li><a href="{% url 'publishes' %}">Publishes</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'profile-page' %}">Profile</a></li>
                <li><a href="{% url 'profile-create' %}">Modify profile</a></li>
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li>
            {% endif %}

        </ul>
    </div>
</nav>

<ul id="slide-out" class="sidenav">
    <li>
        <div class="user-view">
            <div class="background">
                <img src="{% static 'img/library.jpeg' %} " alt="Side background">
            </div>
            <a href="#"><img class="circle" src="{% static 'img/admin.png' %}" alt="Side User Photo"></a>
            <a href="#"><span class="white-text name">User Library</span></a>
            <a href="#"><span class="white-text email">user_email@gmail.com</span></a>
        </div>
    </li>
    <li><a href="#"><i class="material-icons">library_books</i>My Library</a></li>
    <li><a href="#">Second Link</a></li>
    <li>
        <div class="divider"></div>
    </li>
    <li><a class="subheader">Subheader</a></li>
    <li><a class="waves-effect" href="#">Third Link With Waves</a></li>
</ul>
<div class="preloader">
    <div class="preloader-wrapper big active">
        <div class="spinner-layer spinner-blue">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div>
            <div class="gap-patch">
                <div class="circle"></div>
            </div>
            <div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>
</div>


<main>
    {% block library %}{% endblock %}
    {% block login-user %}{% endblock %}
    {% block register-user %}{% endblock %}
    {% block profile-user %}{% endblock %}
    {% block profile-create %}{% endblock %}

    {% block author_list %}{% endblock %}
    {% block publishes %}{% endblock %}
    {% block edit_author %}{% endblock %}
    {% block manage_authors %}{% endblock %}
    {% block manage_books_authors %}{% endblock %}
</main>

<footer class="page-footer purple lighten-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">My Home Virtual Library</h5>
                <p class="grey-text text-lighten-4">
                    If you have any questions, please contact me in slack <b>@<i>Stepan Kozurak</i></b>.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li>To see my code click
                        <a class="grey-text text-lighten-3" href="https://github.com/dannycrief/my_site">
                            here
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © {% now "Y" %} All rights reserved.
            <a class="grey-text text-lighten-4 right" href="#">Stepan Kozurak</a>
        </div>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
{#<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"#}
{#        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"#}
{#        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"#}
{#        crossorigin="anonymous"></script>#}

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

my_site/p_library/templates/author_edit.html
{% extends 'author-base.html' %}
{% block edit_author %}
    <div class="container"
         style="display: flex; justify-content: center; align-items: center;"
    >
        <div class="row"
             style="width: 30rem;"
        >
            <div class="col s12 m12 l12">
                <form method="post"
                      style="display: flex; flex-direction: column; justify-content: center"
                >
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit"
                           value="Save"
                           style="align-self: center; width: 6rem; color: #fff;"
                           class="waves-effect waves-light btn-small"
                    >
                </form>
            </div>
        </div>
    </div>
{% endblock %}

my_site/p_library/templates/author_list.html
{% extends 'author-base.html' %}
{% block author_list %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <ul class="collection">
                    {% for author in object_list %}

                        <li class="collection-item avatar">
                            <img src="images/yuna.jpg" alt="" class="circle">
                            <span class="title">{{ author.full_name }}</span>
                            <p>First Line <br>
                                Second Line
                            </p>
                            <a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

my_site/p_library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {#  bootstrap  #}
    {#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"#}
    {#          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">#}
    {#  materializecss  #}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/media' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>My Home Virtual Library</title>
</head>
<body>
<nav>
    <div class="nav-wrapper purple darken-2">
        <a href="{% url 'my-library' %}" class="brand-logo">My Home Virtual Library</a>
        <a href="#" data-target="slide-out" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'author_list' %}">Authors</a></li>
            <li><a href="{% url 'author_create' %}">Add Author</a></li>
            <li><a href="{% url 'author_book_create_many' %}">Add Book</a></li>
            <li><a href="{% url 'publishes' %}">Publishes</a></li>
        </ul>
    </div>
</nav>

<ul id="slide-out" class="sidenav">
    <li>
        <div class="user-view">
            <div class="background">
                <img src="{% static 'img/library.jpeg' %} " alt="Side background">
            </div>
            <a href="#"><img class="circle" src="{% static 'img/admin.png' %}" alt="Side User Photo"></a>
            <a href="#"><span class="white-text name">User Library</span></a>
            <a href="#"><span class="white-text email">user_email@gmail.com</span></a>
        </div>
    </li>
    <li><a href="#"><i class="material-icons">library_books</i>My Library</a></li>
    <li><a href="#">Second Link</a></li>
    <li>
        <div class="divider"></div>
    </li>
    <li><a class="subheader">Subheader</a></li>
    <li><a class="waves-effect" href="#">Third Link With Waves</a></li>
</ul>
<div class="preloader">
    <div class="preloader-wrapper big active">
        <div class="spinner-layer spinner-blue">
            <div class="circle-clipper left">
                <div class="circle"></div>
            </div>
            <div class="gap-patch">
                <div class="circle"></div>
            </div>
            <div class="circle-clipper right">
                <div class="circle"></div>
            </div>
        </div>
    </div>
</div>


<main>
    {% block index %}{% endblock %}
    {% block author_list %}{% endblock %}
    {% block publishes %}{% endblock %}
    {% block edit_author %}{% endblock %}
    {% block manage_authors %}{% endblock %}
    {% block manage_books_authors %}{% endblock %}
</main>

<footer class="page-footer purple lighten-2">
    <div class="container">
        <div class="row">
            <div class="col l6 s12">
                <h5 class="white-text">My Home Virtual Library</h5>
                <p class="grey-text text-lighten-4">
                    If you have any questions, please contact me in slack <b>@<i>Stepan Kozurak</i></b>.</p>
            </div>
            <div class="col l4 offset-l2 s12">
                <h5 class="white-text">Links</h5>
                <ul>
                    <li>To see my code click
                        <a class="grey-text text-lighten-3" href="https://github.com/dannycrief/my_site">
                            here
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-copyright">
        <div class="container">
            © {% now "Y" %} All rights reserved.
            <a class="grey-text text-lighten-4 right" href="#">Stepan Kozurak</a>
        </div>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
{#<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"#}
{#        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"#}
{#        crossorigin="anonymous"></script>#}
{#<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"#}
{#        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"#}
{#        crossorigin="anonymous"></script>#}

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

my_site/p_library/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block index %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <table class="responsive-table striped">
                    <thead>
                    <tr>
                        <th>Image</th>
                        <th>Book</th>
                        <th>ISBN</th>
                        <th>Description</th>
                        <th>Year Release</th>
                        <th>Author</th>
                        <th>Country</th>
                        <th>Copy Count</th>
                        <th>Redaction</th>
                        <th>Reader</th>
                        <th>Change Count</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for book in books %}
                        <tr>
                            <td>
                                <img src="{{ book.image.url }}"
                                     alt="Book image"
                                     style="max-width: 3rem"
                                     class="materialboxed"
                                >
                            </td>
                            <td>{{ book.title }}</td>
                            <td>{{ book.ISBN }}</td>
                            <td><p>{{ book.description }}</p></td>
                            <td>{{ book.year_release }}</td>
                            <td>{{ book.author.full_name }}</td>
                            <td>{{ book.author.country }}</td>
                            <td>{{ book.copy_count }}</td>
                            <td>{{ book.redaction }}</td>
                            <td>
                                {% if book.reader %}
                                    {{ book.reader }}
                                {% else %}
                                    Book is free
                                {% endif %}
                            </td>
                            <td>
                                <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="hidden" name="id" value="{{ book.id }}"/>
                                    <button class="btn purple lighten-2 waves-effect waves-light" type="submit"
                                            name="action"
                                            value="{{ book.id }}">
                                        Increase
                                    </button>
                                </form>
                                <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="hidden" name="id" value="{{ book.id }}"/>
                                    <button class="btn purple lighten-2 waves-effect waves-light" type="submit"
                                            name="action"
                                            value="{{ book.id }}">
                                        Decrease
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

my_site/p_library/templates/library.html
{% extends 'author-base.html' %}
{% load static %}
{% block library %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12">
                <table class="responsive-table striped">
                    <thead>
                    <tr>
                        <th>Image</th>
                        <th>Book</th>
                        <th>ISBN</th>
                        <th>Description</th>
                        <th>Year Release</th>
                        <th>Author</th>
                        <th>Country</th>
                        <th>Copy Count</th>
                        <th>Redaction</th>
                        <th>Reader</th>
                        <th>Change Count</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for book in books %}
                        <tr>
                            <td>
                                <img src="{{ book.image.url }}"
                                     alt="Book image"
                                     style="max-width: 3rem"
                                     class="materialboxed"
                                >
                            </td>
                            <td>{{ book.title }}</td>
                            <td>{{ book.ISBN }}</td>
                            <td><p>{{ book.description }}</p></td>
                            <td>{{ book.year_release }}</td>
                            <td>{{ book.author.full_name }}</td>
                            <td>{{ book.author.country }}</td>
                            <td>{{ book.copy_count }}</td>
                            <td>{{ book.redaction }}</td>
                            <td>
                                {% if book.reader %}
                                    {{ book.reader }}
                                {% else %}
                                    Book is free
                                {% endif %}
                            </td>
                            <td>
                                <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="hidden" name="id" value="{{ book.id }}"/>
                                    <button class="btn purple lighten-2 waves-effect waves-light" type="submit"
                                            name="action"
                                            value="{{ book.id }}">
                                        Increase
                                    </button>
                                </form>
                                <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="hidden" name="id" value="{{ book.id }}"/>
                                    <button class="btn purple lighten-2 waves-effect waves-light" type="submit"
                                            name="action"
                                            value="{{ book.id }}">
                                        Decrease
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

my_site/p_library/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block login-user %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Log in">
    </form>
{% endblock %}

my_site/p_library/templates/manage_authors.html
{% extends 'author-base.html' %}
{% block manage_authors %}
    <form method="post">
        {% csrf_token %}
        {% for form in author_formset %}
            {{ form.as_ul }}
            <br>
        {% endfor %}
        <input type="submit" value="Save">
    </form>
{% endblock %}

my_site/p_library/templates/manage_books_authors.html
{% extends 'author-base.html' %}
{% block manage_books_authors %}
    <form method="post">
        {% csrf_token %}
        {% for form in author_formset %}
            {{ form.as_ul }}
            <br>
        {% endfor %}

        {% for form in book_formset %}
            {{ form.as_ul }}
            <br>
        {% endfor %}
        <input type="submit" value="Сохранить"/>
    </form>
{% endblock %}

my_site/p_library/templates/profile-create.html
{% extends 'author-base.html' %}
{% load static %}
{% block profile-create %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12"
                 style="display:flex; flex-direction: column; align-items: center;"
            >
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_ul }}
                    <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                        <i class="material-icons right">send</i>
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

my_site/p_library/templates/profile.html
{% extends 'author-base.html' %}
{% load static %}
{% block profile-user %}
    <div class="container">
        <div class="row">
            <div class="col s12 m12 l12"
                 style="display:flex; flex-direction: column; align-items: center;"
            >
                {% if username %}
                    <h1>
                        Hello, {{ username }}!
                    </h1>
                    {% if github_url %}
                        <p>I know your: <a href="{{ github_url }}">GitHub</a> profile!</p>
                    {% endif %}
                    {% if age %}
                        <p>You are {{ age }} years old</p>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

my_site/p_library/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block register-user %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_ul }}
        <input type="submit" value="Register">
    </form>
{% endblock %}